variable:
  profiles: dev

server:
  port: 8184
spring:
  application:
    name: oa-center
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      probability: 1
      percentage: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: '*'


api:
  author-name: mrtang
  reason-content: only play
