server:
  port: 8184
spring:
  application:
    name: oa-center
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: '*'


api:
  author-name: mrtang
  reason-content: only play
