variable:
  profiles: dev

server:
  port: 8184
spring:
  application:
    name: oa-center
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver

  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      probability: 1
      percentage: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true
    
# ====================MybatisPlus====================
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  typeAliasesPackage: com.oa.center.dto.rsp
  mapper-locations: classpath:/mapper/*.xml


management:
  endpoints:
    web:
      exposure:
        include: '*'


api:
  author-name: mrtang
  reason-content: only play
