variable:
  profiles: dev

server:
  port: 9002
spring:
  application:
    name: oa-center
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: '*'


api:
  author-name: '{cipher}cf71679f338d9132c0211a13b9dacdd82cb59cc33a9b1e0ed25239961248b354dfb5177ae20bcf2eb41b1da77a93b1c3'
  reason-content: my job is basketball
  

